FROM php:7.4-apache

RUN a2enmod rewrite

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    zip \
    curl \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libzip-dev \
    libonig-dev \
    libxml2-dev \
 && docker-php-ext-configure gd --with-freetype --with-jpeg \
 && docker-php-ext-install \
    mysqli \
    mbstring \
    gd \
    zip \
    dom \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# install composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# dev php settings
RUN { \
    echo 'display_errors=On'; \
    echo 'display_startup_errors=On'; \
    echo 'error_reporting=E_ALL'; \
    echo 'log_errors=On'; \
    echo 'html_errors=On'; \
} > /usr/local/etc/php/conf.d/dev.ini